insert into us_states
  (us_state, full_name, neighboring_states)
values
  ('AL', 'Alabama', '{"FL", "GA", "TN", "MS"}'),
  ('AK', 'Alaska', '{}'),
  ('AR', 'Arkansas', '{"LA","MS","TN","MO","OK","TX"}'),
  ('AZ', 'Arizona', '{"NM","UT","NV","CA"}'),
  ('CA', 'California', '{"AZ","NV","OR"}'),
  ('CO', 'Colorado', '{"NM","OK","KS","NE","WY","UT"}'),
  ('CT', 'Connecticut', '{"RI","MA","NY"}'),
  ('DC', 'District of Colombia', '{"VA","PA"}'),
  ('DE', 'Delaware', '{"NJ","PA","MD"}'),
  ('FL', 'Florida', '{"GA","AL"}'),
  ('GA', 'Georgia', '{"SC","NC","TN","AL","FL"}'),
  ('HI', 'Hawaii', '{}'),
  ('ID', 'Idaho', '{"WA","OR","NV","UT","WY","MT"}'),
  ('IL', 'Illinois', '{"WI","IA","MO","KY","IN"}'),
  ('IN', 'Indiana', '{"IL","KY","OH","MI"}'),
  ('IA', 'Iowa', '{"MN","SD","NE","MO","IL","WI"}'),
  ('KS', 'Kansas', '{"OK","MO","NE","CO"}'),
  ('KY', 'Kentucky', '{"TN","VA","WV","OH","IN"}'),
  ('LA', 'Louisiana', '{"MS","AR","TX"}'),
  ('ME', 'Maine', '{"NH"}'),
  ('MD', 'Maryland', '{"DE","PA","WV","VA"}'),
  ('MA', 'Massachusetts', '{"NH","VT","NY","CT","RI"}'),
  ('MI', 'Michigan', '{"WI","IN","OH"}'),
  ('MN', 'Minnesota', '{"ND","SD","IA","WI"}'),
  ('MO', 'Missouri', '{"AR","TN","KY","IL","IA","NE","KS","OK"}'),
  ('MS', 'Mississippi', '{"AL","TN","AR","LA"}'),
  ('MT', 'Montana', '{"ID","WY","SD","ND"}'),
  ('NE', 'Nebraska', '{"KS","MO","IA","SD","WY","CO"}'),
  ('NV', 'Nevada', '{"AZ","UT","ID","OR","CA"}'),
  ('NH', 'New Hampshire', '{"VT","MA","ME"}'),
  ('NJ', 'New Jersey', '{"NY","PA","DE"}'),
  ('NM', 'New Mexico', '{"AZ","CO","OK","TX","UT"}'),
  ('NY', 'New York', '{"PA","NJ","CT","MA","VT"}'),
  ('NC', 'North Carolina', '{"VA","TN","GA","SC"}'),
  ('ND', 'North Dakota', '{"MT","SD","MN"}'),
  ('OH', 'Ohio', '{"MI","IN","KY","WV","PA"}'),
  ('OK', 'Oklahoma', '{"TX","AR","MO","KS","CO","NM"}'),
  ('OR', 'Oregon', '{"CA","NV","ID","WA"}'),
  ('PA', 'Pennsylvania', '{"OH","WV","MD","DE","NJ","NY"}'),
  ('RI', 'Rhode Island', '{"MA","CT"}'),
  ('SC', 'South Carolina', '{"GA","NC"}'),
  ('SD', 'South Dakota', '{"NE","IA","MN","ND","MT","WY"}'),
  ('TN', 'Tennessee', '{"AL","GA","NC","VA","KY","MO","AR","MS"}'),
  ('TX', 'Texas', '{"LA","AR","OK","NM"}'),
  ('UT', 'Utah', '{"AZ","CO","WY","ID","NV"}'),
  ('VA', 'Virgina', '{"MD","WV","KY","TN","NC"}'),
  ('VT', 'Vermont', '{"NY","MA","NH"}'),
  ('WA', 'Washington', '{"OR","ID"}'),
  ('WV', 'West Virigina', '{"VA","MD","PA","OH","KY"}'),
  ('WI', 'Wisconsin', '{"MN","IA","IL","MI"}'),
  ('WY', 'Wyoming', '{"CO","NE","SD","MT","ID","UT"}')
  ;
